name: Issue Report
description: What went wrong
title: "[Issue]: "
labels: [bug, triage, issue, defect]
assignees:
  - vfs-sct
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Reported By
      description: Who found this issue?
      placeholder: GD24_Joe
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Breif Description
      description: What happened?
      placeholder: Game failed to start on Pressed start and it failed to start
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severits
      description: How does this affect the game functionality
      options:
        - A - Crash/Legal
        - B - Major
        - C - Minor
        - D - Cosmetic
        - E - Feature
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is the issue to the overall experience
      options:
        - 1 - Critical
        - 2 - High
        - 3 - Medium
        - 4 - Low
        - 5 - Unimportant
    validations:
      required: true
  - type: dropdown
    id: game-area
    attributes:
      label: Game Area
      description: What is the primary game ara affected
      options:
        - Characters
        - Animation
        - Cameras
        - Controls
        - Gameplay
        - Front-End, HUD, Overlays
        - Levels (Environment)
        - Gameplay AI
        - Multiplayer or Network
        - VFX
        - Audio
    validations:
      required: true
  - type: dropdown
    id: reproducability
    attributes:
      label: Reproducability
      description: How often does it happen?
      options:
        - Always
        - Frequently
        - Occasionally
        - Rarely
        - Once
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Reproduction steps?
      description: Describe what you did, what happened and what you expected to happen?
      placeholder: Tell us what you see!
      value: "- I pressed start and it didn't start!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which milestone and build (id) were you playing?
      placeholder: M1 0.1.1234
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
